addView("1.3.3", "7 June 2017", "- Code cleaning")
addView("1.3.2", "17 Apr. 2017", "- Fixed respring bug on iOS 9.1")
addView("1.3.1", "5 Apr. 2017", "- Fixed a memory leak... Oops")
addView("1.3", "1 Apr. 2017", "- Activator isn't a dependency anymore")
addView("1.2.1", "24 Feb. 2017", "- Minor fix<br>- Added Arabic translation")
addView("1.2", "23 Feb. 2017", "- Now Sensible will automatically disable reachability<br>- Fixed default language<br>- Fixed a bug on iPhone 6 or newer")
addView("1.1", "21 Feb. 2017", "- Clean up code<br>- Bug fixes<br>")
addView("1.0", "10 Feb. 2017", "- Stable version<br>- Preference pane added<br>- Bug fixes<br>")
addView("0.1 Alpha", "16 Jan. 2017", "- First version<br>- Sensible is working and tested on iOS 9<br>- Give an sweet haptic feedback<br>I will add a preference pane for the next update")
